### ISSUE TITLE
Fields seem to be missing

### ISSUE THREAD

**Issue by daveybrown** [pristas-peter/wp-graphql-gutenberg#1]
**Expected Behavior**

An attributes field is available on blocks

**Current Behavior**

The only fields available are

    isValid
    name
    originalContent
    innerBlocks
          
**Steps to Reproduce**

1. Install WP GraphQL, WP GraphQL Gutenberg & WP GraphiQL
2. Edit and update the only post
3. Explore using GraphiQL

![image](https://user-images.githubusercontent.com/15802017/56641279-ec642d00-666c-11e9-971a-39a15434c3d5.png)

**Context**

A fresh install no other plugins, on dev environment, WordPress fpm and nginx.

I'm available on https://wp-graphql.slack.com ( [join](https://wpgql-slack.herokuapp.com/) ) if I can be of any help. Thanks,

**Comment by pristas-peter** [comment]
You have to query like this: 
```graphql
{
  posts(first: 2) {
    edges {
      node {
        content
        blocks {
          isValid
          ... on CoreParagraphBlock {
            attributes {
              ... on CoreParagraphBlockAttributesV3 {
                align
                dropCap
                backgroundColor
              }
            }
          }
        }
      }
    }
  }
}

```

**Comment by pristas-peter** [comment]
@daveybrown I will explain the V2, V3 suffix in README (it's due to breaking changes in deprecations and there is no another way how to type this correctly).

**Comment by daveybrown** [comment]
Awesome, thank you!
