### ISSUE TITLE
Conflict with wpgraphql new version and graphql IDE not working

### ISSUE THREAD

**Issue by shrenikTrukky** [pristas-peter/wp-graphql-gutenberg#116]
WPGraphQL IDE not working with current wp-graphql-gutenberg version. showing error in console panel. 
<img width="1440" alt="Screenshot 2021-07-30 at 9 50 46 AM" src="https://user-images.githubusercontent.com/15668512/128284750-e4d251cb-b3e5-4da9-a006-e0b7ee4fd441.png">

**Comment by jonsherrard** [comment]
@shrenikTrukky having worked with this plugin for the last week I can tell you it's so so SO finicky to get working.

Reason's it may not be wroking:

- PHP Version
- WP Version
- WP GraphQL Plugin Version
- Integration with other plugins like ACF

I recommend you add GRAPHQL_DEBUG, TRUE, to your ENV or wp-config for more information.

**Comment by shrenikTrukky** [comment]
> @shrenikTrukky having worked with this plugin for the last week I can tell you it's so so SO finicky to get working.
> 
> Reason's it may not be wroking:
> 
> * PHP Version
> * WP Version
> * WP GraphQL Plugin Version
> * Integration with other plugins like ACF
> 
> I recommend you add GRAPHQL_DEBUG, TRUE, to your ENV or wp-config for more information.

PHP Version 7.4.1
WP Version 5.8
WP GraphQL Plugin Version 1.6.2
All other plugins are disabled and checked still happen this error and GRAPHQL_DEBUG already TRUE.

**Comment by jasonbahl** [comment]
👋🏻 I have a PR that I believe resolves the incompatibility with WPGraphQL v1.6: https://github.com/pristas-peter/wp-graphql-gutenberg/pull/117
