### ISSUE TITLE
PHP Min Version

### ISSUE THREAD

**Issue by freddiemixell** [pristas-peter/wp-graphql-gutenberg#13]
Hey all,

I love this plugin so I'm not trying to be a complainer because I really appreciate the work you've done. I just wanted to note that the use of dangle commas in PHP are specific to php 7.3.

I was running 7.2 and had an error when I tried to activate the plugin due to the dangle comma on line 462. I knew what it was right away and upgraded my dev environment to 7.3 but I think a notice could help newer developers, or Javascript developers that aren't familiar with PHP, get started with this repo.

I'm only posting because I think that this is a much better pattern for reusability imho for Gutenberg blocks and I'd like to see more people using it!

Cheers,
Freddie

PS: I'll make a PR for a notice if you'd like :)

**Comment by pristas-peter** [comment]
Oh yes, sorry about this. I will fix this immediately, but for the long run I should run the code through some phplinter when committing.

**Comment by pristas-peter** [comment]
Fixed in #15

**Comment by freddiemixell** [comment]
@pristas-peter thanks homie!
