### ISSUE TITLE
Warning ! heuristic fragment matching going on !

### ISSUE THREAD

**Issue by cfabrice** [pristas-peter/wp-graphql-gutenberg#14]
Hello, great extension !
I query the post as in your example using fragment... but I then I got this error ! 
By the way, i'm trying to loop over the blocks and use matching name components. This is fine but instead of accessing the raw content of the block (which I could if the queries with fragment would work) I ended up doing some bad regex based extraction to get the source of an image block for example... 
I've read that I should use "IntrospectionFragmentMatcher" but it is way out of my skills is there a way to silence this warning as this request is just to display some part of the post and will never alter the post... The funny thing is that with graphiql, within worpdress, the queries works without warning. 
Or, do you have simple example with this "introspectionFragmentMatcher" ? 
<img width="2088" alt="Capture d’écran 2019-11-11 à 00 44 20" src="https://user-images.githubusercontent.com/1519779/68572713-6c65af00-0466-11ea-9dc0-5f2c0ae3e33e.png">
Thank you anyway.

**Comment by pristas-peter** [comment]
Hello, thanks.

You need to setup a build step which generates the introspection json file and load it to the apollo client. You can find more info and setup here:
https://graphql-code-generator.com/docs/plugins/fragment-matcher

More info in the official docs:
https://www.apollographql.com/docs/react/data/fragments/

**Comment by cfabrice** [comment]
I’ll look into it. 
Thank you for the fast response…
