### ISSUE TITLE
ACF repeater data returns field key and not field names.

### ISSUE THREAD

**Issue by orjanb-ne** [pristas-peter/wp-graphql-gutenberg#16]
Whenever I use ACF repeaters in a block I get field key instead of name.
I use:
WPGraphQL 0.4.0
ACF Pro 5.8.7
WPGraphQL-ACF 0.3.1

**Comment by orjanb-ne** [comment]
Typical data respons
`"{\"field_5d6e521fd60ca\":{\"row-0\":{\"field_5d6e5270d60cb\":\"10000 BC\",\"field_5d6e52b2d60cc\":{\"row-0\":{\"field_5d6e66420030a\":\"1\"},\"row-1\":{\"field_5d6e66420030a\":\"79\"}}},\"row-1\":{\"field_5d6e5270d60cb\":\"5000 BC\",\"field_5d6e52b2d60cc\":{\"row-0\":{\"field_5d6e66420030a\":\"1\"}}}}}"`

**Comment by pristas-peter** [comment]
@orjanb-ne 

Can you post here your graphql query? It seems like you are querying raw acf block data.
Do you also have this plugin installed, which exposes this raw data further in the schema?

https://github.com/pristas-peter/wp-graphql-gutenberg-acf

**Comment by orjanb-ne** [comment]
Ah yes, much better response with that plugin. Thanks!
