### ISSUE TITLE
Images is empty in CoreGalleryBlock

### ISSUE THREAD

**Issue by Okakakai** [pristas-peter/wp-graphql-gutenberg#186]
I am a novice engineer using WordPress with lightsail.
Using WP as a Headless CMS.
I would like to get the url of each image of "CoreGalleryBlock".
However, I get [].
Please let me know the wisdom to get the full url etc.

<img width="638" alt="image" src="https://user-images.githubusercontent.com/50835649/221149901-424ef387-52a0-4e0e-9807-648af91dd247.png">

---
WordPress : Version 6.1.1
WP GraphQL : Version 1.13.6 
WP GraphQL Gutenberg : Version 0.3.11

**Comment by Greaby** [comment]
@Okakakai The format of the CoreGalleryBlock has changed.
```graphql
 blocks {
    ... on CoreGalleryBlock {
        innerBlocks {
            ... on CoreImageBlock  {
                attributes {
                    ... on CoreImageBlockAttributes{
                        alt
                        caption
                        url
                    }
                }
            }
        }
    }
}
```
