### ISSUE TITLE
Attributes for paragraph block nested inside a column block not working

### ISSUE THREAD

**Issue by daveybrown** [pristas-peter/wp-graphql-gutenberg#2]
The attributes for a paragraph block nested inside a column block are not working. 

`__typename` on the attribute field causes an Internal server error.

**Expected Behavior**

Nested paragraph attributes are available - my test shows nested headings and images are working OK.

**Steps to Reproduce**

Create a columns layout block in the editor. Add a heading and paragraph on left, and image block on right.

Running the following query I get the following response.

**Query**

    query pages {
      pageBy( uri: "home") {
        id
        blocks {
          ... on CoreColumnsBlock {
            innerBlocks {
              ... on CoreColumnBlock {
                innerBlocks {
                  ... on CoreHeadingBlock {
                    attributes {
                      ... on CoreHeadingBlockAttributes {
                        content
                      }
                    }
                  }
                  ... on CoreParagraphBlock {
                    originalContent
                    isValid
                    attributes {
                      __typename
                      ... on CoreParagraphBlockAttributesV3 {
                        content
                      }
                    }
                  }
                  ... on CoreImageBlock {
                    attributes {
                      ... on CoreImageBlockAttributes {
                        url
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }

**Response**

    {
      "errors": [
        {
          "message": "Internal server error",
          "category": "internal",
          "locations": [
            {
              "line": 19,
              "column": 17
            }
          ],
          "path": [
            "pageBy",
            "blocks",
            1,
            "innerBlocks",
            0,
            "innerBlocks",
            1,
            "attributes"
          ]
        }
      ],
      "data": {
        "pageBy": {
          "id": "cGFnZTo2MA==",
          "blocks": [
            {},
            {
              "innerBlocks": [
                {
                  "innerBlocks": [
                    {
                      "attributes": {
                        "content": "Our story"
                      }
                    },
                    {
                      "originalContent": "<p>Hi there</p>",
                      "isValid": true,
                      "attributes": null
                    }
                  ]
                },
                {
                  "innerBlocks": [
                    {
                      "attributes": {
                        "url": "http://localhost/wp/wp-content/uploads/2019/04/bay-1787065_1920-1024x683.jpg"
                      }
                    }
                  ]
                }
              ]
            },
            {},
            {},
            {},
            {}
          ]
        }
      }
    }

**Comment by pristas-peter** [comment]
Will look into this. Thanks

**Comment by daveybrown** [comment]
Awesome, cheers!

**Comment by pristas-peter** [comment]
@daveybrown Should work now. But you need to re-save the post you were working on, or rather use the `Update all posts which support editor` button in admin menu.

**Comment by daveybrown** [comment]
Great!
