### ISSUE TITLE
content attribute is not returned for the core/paragraph block

### ISSUE THREAD

**Issue by sathyapulse** [pristas-peter/wp-graphql-gutenberg#206]
The `content` attribute field is not being returned for the `core/paragraph` block. 

The Gutenberg plugin 17.3 merged the PR [#43204](https://github.com/WordPress/gutenberg/pull/43204), which changed the type and source attribute values from `string` => `rich-text` and `html` => `rich-text`, respectively, for the core paragraph block. As a result, the `wp-graphql-gutenberg` plugin fails to identify/parse the content attribute from the paragraph block.

The `content` attribute type doesn't have a matching case for `rich-text` [here](https://github.com/pristas-peter/wp-graphql-gutenberg/blob/bacabca662698871ecc8b297c7af3b5b95d431c1/src/Schema/Types/BlockTypes.php#L44), and it was identified as `string` earlier. Also, the `content` attribute source doesn't have a matching case for `rich-text` [here](https://github.com/pristas-peter/wp-graphql-gutenberg/blob/bacabca662698871ecc8b297c7af3b5b95d431c1/src/Blocks/Block.php#L59), and it was identified as `html` earlier. The `wp-graphql-gutenberg` plugin should patch those to fix the issue.

As I mentioned, the change was made in the Gutenberg 17.3 release, which was shipped with the [WordPress 6.5 release](https://developer.wordpress.org/block-editor/contributors/versions-in-wordpress/).

**Comment by kuuak** [comment]
I encountered the same issue. A PR #203 has however been proposed

**Comment by sathyapulse** [comment]
The PR #203 has been merged. I'm closing the issue. Thanks.
