### ISSUE TITLE
Type conflict when pulling entire schema

### ISSUE THREAD

**Issue by TylerBarnes** [pristas-peter/wp-graphql-gutenberg#22]
Hey Peter!
Hope the new plugin is going well :)
I'm testing out this one with the upcoming `gatsby-source-wordpress@v4`. The new version uses introspection to generate full-schema queries in order to pull the entire WPGQL schema, and while doing so I'm running into some type conflicts.

When I run this query
```graphql
query NODE_LIST_QUERY {
  pages {
    nodes {
      blocks {
        __typename
        ... on CoreParagraphBlock {
          attributes {
            __typename
            ... on CoreParagraphBlockAttributesV2 {
              fontSize
            }
            ... on CoreParagraphBlockAttributesV3 {
              content
              fontSize
            }
          }
        }
        ... on CoreCodeBlock {
          attributes {
            content
          }
        }
      }
    }
  }
}

```

I get these errors:

```json
{
  "errors": [
    {
      "message": "Fields \"attributes\" conflict because subfields \"content\" conflict because they return conflicting types String! and String. Use different aliases on the fields to fetch both if this was intentional.",
      "category": "graphql",
      "locations": [
        {
          "line": 7,
          "column": 11
        },
        {
          "line": 13,
          "column": 15
        },
        {
          "line": 19,
          "column": 11
        },
        {
          "line": 20,
          "column": 13
        }
      ]
    },
    {
      "message": "Fields \"fontSize\" conflict because they return conflicting types Float and String. Use different aliases on the fields to fetch both if this was intentional.",
      "category": "graphql",
      "locations": [
        {
          "line": 10,
          "column": 15
        },
        {
          "line": 14,
          "column": 15
        }
      ]
    }
  ]
}
```

I think it's because different block types that are implementing the Block interface are defining fields with the same name but the fields have different types. Any thoughts on a quick fix? @jasonbahl curious if you have any ideas as well

**Comment by pristas-peter** [comment]
Sorry my chrome tab froze (probably because of that long query :)) after I have written the reply so I took the quick screenshot so I don't have to retype:

<img width="648" alt="Screenshot 2020-01-22 at 06 53 23" src="https://user-images.githubusercontent.com/9489687/72869041-3ce3e600-3ce4-11ea-90ad-9119556acb90.png">

**Comment by TylerBarnes** [comment]
Sorry, just edited the issue 😆 should've done that to begin with!

So I thought about this a bit more and did a deeper dive into the issue and my takeaway is that I should account for this situation in the source plugin (as this will likely be a common error), but I also think the schema here could be a bit more friendly for consumers.
I wonder if Block was a union type instead of an interface it would make for a nicer experience? I believe these kinds of errors wouldn't show up in that case, though I might be wrong about that. Curious what you think!

**Comment by pristas-peter** [comment]
The block attributes are union, the block is an interface because of some common fields you can query on every block nevertheless of its type/name. I kinda think it is handy, because you mostly query an array of blocks and you cannot do that with an union type.

**Comment by TylerBarnes** [comment]
@pristas-peter true, that is useful. @jasonbahl and I just discussed this a bit and we came to the conclusion that using a union type here actually wouldn't help anyway as this is a feature of the GraphQL spec for both unions and interfaces which is meant to ensure type safety for consumers.

If you were to query this:
```graphql
{
  pages {
    nodes {
      parent {
        ... on Page {
          title
        }
        ... on Post {
          title: id
        }
      }
    }
  }
}
```

You get the same error as it's the same problem.
If you check the spec on [field selection merging](http://spec.graphql.org/June2018/#sec-Field-Selection-Merging) and specifically [counter example 112](http://spec.graphql.org/June2018/#example-54e3d) they're saying it will always error. Lee Byron talks about it in [this issue response](https://github.com/graphql/graphql-js/issues/522#issuecomment-255837127) and says the two solutions are to alias the fields so that `FieldsInSetCanMerge(set)` is true or fix it on the server by making the field names unique if the types are different.

So I would say technically this plugin is respecting the GQL spec, but it's in a grey area where running some commonly used queries would be rejected by the server, not because there's anything wrong with the individual selection sets or the data but because the type of the returned data will be too ambiguous.
So the lack of a type registry in Gutenberg is leaking into the attributes field of this plugins schema and causing type uncertainty for consumers.

Jasons proposed solution is to prefix the attributes field name with the name of the parent type, for example `CoreParagraphBlock_attributes` instead of `attributes`. He mentioned this is what he had to do for the ACF WPGQL plugin. It would be a breaking change but surely a good one for consumers as no queries would error out.

**Comment by pristas-peter** [comment]
Yeah it is not a problem for myself or the plugin and i can change it, however I think you will run into this problem when using other plugins, when you don't have the choice to modify the source. I kinda think you should do this on your side when creating the query - map all the union types or types that implement the interface and prefix all the fields which you query with its typename. Does that make sense?

I am not planning to deprecate this plugin, but within gatsby I will encourage people to use the 
new native source plugin which should not have these problems anyway.

**Comment by TylerBarnes** [comment]
I agree 100%. Good to hear you're open to that changing in the schema. I can try making a PR for it. Also good to hear the new plugin doesn't have these issues 👍 
Thinking about it a bit more, I think it would also need to change for versioned block attributes like so:

```graphql
{
  pages {
    nodes {
      blocks {
        __typename
        ... on CoreParagraphBlock {
          CoreParagraphBlock_attributes {
            fontSize
          }
          CoreParagraphBlockV2_attributes {
            fontSize
          }
          CoreParagraphBlockV3_attributes {
            fontSize
          }
        }
        ... on CoreCodeBlock {
          CoreCodeBlock_attributes {
            content
          }
        }
      }
    }
  }
}
```

**Comment by pristas-peter** [comment]
Also just to note that the parent on the block is a cyclic reference to a graphql post type which exposes blocks in the first place. How do you handle these situations?

**Comment by TylerBarnes** [comment]
I analyze the schema ahead of time to determine which types will be Gatsby nodes in the future, and if any field is a connection to a future Gatsby node I just pull the id and replace the connection on the Gatsby side. I have a configurable query depth for cases where it would potentially be an infinitely nested query

**Comment by TylerBarnes** [comment]
The nice thing about that is it potentially leads to even less fetching than using WPGQL normally

**Comment by pristas-peter** [comment]
Yeah sounds great.

**Comment by jaredcbaum** [comment]
This is still a problem. Not sure if it's inherent to graphql, but I used aliasing to get to where I wanted.
For example on my code component I aliased the content to `codeContent` like this:
```
attributes {
  codeContent: content
}
```
