### ISSUE TITLE
 Could not determine type of attribute "figureStyle" in "core/pullquote" block type

### ISSUE THREAD

**Issue by ktw-studio** [pristas-peter/wp-graphql-gutenberg#31]
Hey, 

I am experiencing some problems with the pullquote block. When WP_DEBUG is enabled I get the following warning:
> Could not determine type of attribute "figureStyle" in "core/pullquote" block type
What is the point of this warning and how could I help to modify the function to handle blocks that do not have 'type' field.

Kind regards,
M

**Comment by pristas-peter** [comment]
Hi this is fixed in new version (0.2) coming out this week. You can checkout develop branch if you need it right away.

**Comment by ktw-studio** [comment]
Cool, I will check it out! :)
