### ISSUE TITLE
Trailing slash in function

### ISSUE THREAD

**Issue by mmazurowski** [pristas-peter/wp-graphql-gutenberg#32]
Hey, 

I just wanted to say that I found a problem when running plugin which seems easy to fix. 
Line 32 in this file: https://github.com/pristas-peter/wp-graphql-gutenberg/blob/develop/src/Schema/Utils.php

Just delete trailing coma and the warning is gone.
Cheers!

**Comment by pristas-peter** [comment]
thanks i will definitely run the code through some linter before making a release, which should remove all those commas in codebase.

Thanks for the reminder
