### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function WPGraphQLGutenberg\Schema\Types\Scalar\register_graphql_scalar()

### ISSUE THREAD

**Issue by ktw-studio** [pristas-peter/wp-graphql-gutenberg#37]
Hi, 

When using current master I get the following error:

`Fatal error: Uncaught Error: Call to undefined function WPGraphQLGutenberg\Schema\Types\Scalar\register_graphql_scalar() in wp-graphql-gutenberg-master/src/Schema/Types/Scalar/Scalar.php on line 12`

Any idea what could make it happen? 

Kind regards,
M

**Comment by pristas-peter** [comment]
Yeah you need to upgrade to wp-graphql 0.8.4

**Comment by ktw-studio** [comment]
Seems to work like a charm, I need to buy you a beer when this coronavirus things goes out!
