### ISSUE TITLE
[Question] Not working with custom post types

### ISSUE THREAD

**Issue by rtsilva-daitan** [pristas-peter/wp-graphql-gutenberg#4]
I've created a CPT named News, I've set support to editor,  show_in_graphql, show_in_rest.
All working with graphql. But when query blocks I get `Cannot query field \"blocks\" on type \"News\".`

Is there any setting I may have forgotten?

**Comment by CHEWX** [comment]
Hi,

Are they named the same? 

What's your `register_post_type( 'xxx', $args );` and 'graphql_single_name' => 'xxx', values set to? If they are different it won't work.

Thanks,
Tom

**Comment by pristas-peter** [comment]
@rtsilva-daitan  Sorry I have missed the PR notification so I'm responding late. Yes @CHEWX is right. Should fix that though.

**Comment by CHEWX** [comment]
@pristas-peter If possible as I personally set my register to `cpt_xxx` and then graphql_single_name to `xxx`.

**Comment by rtsilva-daitan** [comment]
@CHEWX @pristas-peter Yeah, I haven't notice that. My ```graphql_single_name``` was capitalized :man_facepalming:

Thank you guys

**Comment by CHEWX** [comment]
I'm not sure this should be closed, it's a bug really. `wpgraphql` doesn't have this stipulation of matching post type name, nor should this as it doesn't give flexibility to the developer and mistakes will be made easily.
