### ISSUE TITLE
Internal server error when quering blocks

### ISSUE THREAD

**Issue by ktw-studio** [pristas-peter/wp-graphql-gutenberg#45]
Hi, 

It's me again. I have updated the plugin to the latest version as well as pulled requested plugin dependencies:
WP GraphQL 0.9.1
WP GraphQL Gutenberg 0.3.1
WP GraphQL GutenbergACF 0.3.0

I can't query any block. I get the following response on page query no matter what client I use(Postman, GraphQL, Gatsby GraphQL Client)
```{
  "errors": [
    {
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 4,
          "column": 7
        }
      ],
      "path": [
        "pages",
        "nodes",
        0,
        "blocks"
      ]
    }
  ],
  "data": {
    "pages": {
      "nodes": [
        {
          "blocks": null,
          "id": "cG9zdDozODU="
        }
      ]
    }
  }
}
```

Example query:
`query MyQuery {
      pages {
      nodes {
        id
        blocks {
          name
        }
      }
    }
}
`

Kind regards,
Marcin

**Comment by dannyvaughton** [comment]
Also getting this error.

Using:

WP GraphQL 0.9.1
WP GraphQL Gutenberg 0.3.1
WP GraphQL GutenbergACF 0.3.1

**Comment by dannyvaughton** [comment]
To expand on my previous comment, I am getting this error on the /graphql endpoint:

Fatal error: Uncaught Error: Call to undefined function WPGraphQLGutenberg\Schema\Types\Scalar\register_graphql_scalar() in /Users/danny/Local Sites/rentivo-simba/app/public/wp-content/plugins/wp-graphql-gutenberg-0.3.1/src/Schema/Types/Scalar/Scalar.php on line 8

**Comment by pristas-peter** [comment]
Hi guys, do hou install the plugin via composer, or just downloaded the zip file from releases?

**Comment by ktw-studio** [comment]
In my case downloaded zip from the todays master.

**Comment by xJAS3x** [comment]
> Hi guys, do you install the plugin via composer, or just downloaded the zip file from releases?

I am getting "Internal server error" with block vaules of "null". I also used the 0.3.1 .zip file.

**Comment by Gurakh** [comment]
Hi ! Same error here when installing the 0.3.1 version with composer.

**Comment by pristas-peter** [comment]
I have pushed into the master and recreated the v0.3.1 release with the fix:
https://github.com/pristas-peter/wp-graphql-gutenberg/releases/tag/v0.3.1

Please try and let me know. Thanks.

Note: You also need to use wp-graphql 0.9.0 or above.

**Comment by xJAS3x** [comment]
> I have pushed into the master and recreated the v0.3.1 release with the fix:
> https://github.com/pristas-peter/wp-graphql-gutenberg/releases/tag/v0.3.1
> 
> Please try and let me know. Thanks.
> 
> Note: You also need to use wp-graphql 0.9.0 or above.

![image](https://user-images.githubusercontent.com/16025417/83579427-40477380-a507-11ea-8a47-931124d56304.png)

Data is now accessible. Thanks!
