### ISSUE TITLE
Activating changes the language of the block editor

### ISSUE THREAD

**Issue by qrac** [pristas-peter/wp-graphql-gutenberg#49]
Hello. Thanks for the great plugin!

By the way, activating the plugin changes some of the language in Gutenberg.
My WordPress is in Japanese, but it has English mixed in.

![image](https://user-images.githubusercontent.com/9658016/84467672-cc9c2800-acb7-11ea-9245-86f635c6ace8.png)

It's not a fatal problem, but is there a solution?

---

- WordPress: v5.4.2
- WP GraphQL: v0.9.1
- WP GraphQL Gutenberg: v0.3.1
- Mac: v10.15.5
- Chrome: v83.0.4103.97

**Comment by pristas-peter** [comment]
Thanks. I will have a look why this happens.

**Comment by qrac** [comment]
Wonderful...! v0.3.2 solved the problem.
Thanks for the quick fix!

**Comment by pristas-peter** [comment]
Happy to hear that. Enjoy
