### ISSUE TITLE
core/freeform not available in blocks and previewBlocks

### ISSUE THREAD

**Issue by gustavarrhenius** [pristas-peter/wp-graphql-gutenberg#52]
Since Wordpress returns `blockName=>null` on `core/freeform` when using `parse_blocks` the block wont appear in the blocks and previewBlocks field. 

`/src/Blocks/Block.php` on line 16 jumps over blocks with name that are empty.

How do you suggest the best way is to expose that block?

**Comment by gustavarrhenius** [comment]
Btw i noticed that it works when added to a column block, but not when added to the root of content.

**Comment by pristas-peter** [comment]
Thanks for the issue, I have added a fix which does kinda the same logic as the JS parser in gutenberg.
