### ISSUE TITLE
The 0.3.4 tagged version is using 0.3.3 code

### ISSUE THREAD

**Issue by jacobarriola** [pristas-peter/wp-graphql-gutenberg#55]
Hi there!

I'm downloading a zip of 0.3.4 but the code reflects version 0.3.3.

Steps to reproduce:
- Visit https://github.com/pristas-peter/wp-graphql-gutenberg/releases/tag/v0.3.4
- Download 'Source Code (zip)

For now I'm just grabbing the zip of the `develop` branch.

Thanks!

**Comment by pristas-peter** [comment]
Thanks for reporting this, the PR to master was not merged for some reason.
