### ISSUE TITLE
Content editor whitescreen: The editor has encountered an unexpected error.

### ISSUE THREAD

**Issue by jacobarriola** [pristas-peter/wp-graphql-gutenberg#56]
Hey there!

For some reason, the content editor fails to load when this plugin is activated 🤔. This is for Pages and Posts.

![image](https://user-images.githubusercontent.com/1371573/85780460-7ed0e800-b6d9-11ea-8df4-cfaa607e94c7.png)

What's the best way to troubleshoot this?

FYI - I am able to run queries on a page with blocks via GraphiQL on WordPress.
![image](https://user-images.githubusercontent.com/1371573/85780403-6eb90880-b6d9-11ea-8777-4e62363b373e.png)

Using:
-wp-graphql: 0.9.1
-wp-gatsby: 0.4.1
-wp-graphql-gutenberg: 0.3.4
-Wordpress: 5.2.4

The dialogue that pops up allows me to copy the error. Here's the dump of that:

```
ue@*****/wp-content/plugins/wp-graphql-gutenberg-0.3.4/build/index.js?ver=fd9cc99659d1d150b19d0f988a85b971:24:8591
Td@*****/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:82:11
hi@*****/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:102:385
Qg@*****/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:144:219
Rg@*****/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:145:76
Sc@*****/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:158:109
Z@*****/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:156:494
Kc@*****/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:155:52
ya@*****/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:153:159
enqueueSetState@*****/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:202:411
t.prototype.setState@*****/wp-includes/js/dist/vendor/react.min.js?ver=16.8.4:20:433
value@*****/wp-includes/js/dist/data.min.js?ver=4.4.0:1:16219
value/this.unsubscribe<@*****/wp-includes/js/dist/data.min.js?ver=4.4.0:1:16397
n/<@*****/wp-includes/js/dist/data.min.js?ver=4.4.0:1:11659
n@*****/wp-includes/js/dist/data.min.js?ver=4.4.0:1:11632
m/y</<@*****/wp-includes/js/dist/data.min.js?ver=4.4.0:1:8807
v@*****/wp-includes/js/dist/data.min.js?ver=4.4.0:1:29557
b/</<@*****/wp-includes/js/dist/data.min.js?ver=4.4.0:1:5879
O/</</<@*****/wp-includes/js/dist/data.min.js?ver=4.4.0:1:6307
a/</</<@*****/wp-includes/js/dist/redux-routine.min.js?ver=3.2.0:1:9567
dispatch@*****/wp-includes/js/dist/data.min.js?ver=4.4.0:1:32017
i/<@*****/wp-includes/js/dist/redux-routine.min.js?ver=3.2.0:1:9218
e/<@*****/wp-includes/js/dist/redux-routine.min.js?ver=3.2.0:1:5434
e@*****/wp-includes/js/dist/redux-routine.min.js?ver=3.2.0:1:5410
o/<@*****/wp-includes/js/dist/redux-routine.min.js?ver=3.2.0:1:5364

```

**Comment by pristas-peter** [comment]
Well it might be the wordpress version, it's possible for you to update to 5.4?

**Comment by pristas-peter** [comment]
You can debug the plugin:

go to the plugin's directory and run 
```
npm i
npm run start
```

You will then see development version with better logging. (however source maps should have worked in the first place)

**Comment by jacobarriola** [comment]
I'm going to start with updating the version of WordPress that the instance is running. Stand by 🚀

**Comment by jacobarriola** [comment]
@pristas-peter the update (5.2.4 -> 5.4.1) fixed the issue. Thanks for your quick response!

FWIW, when I debugged the issue, looks like this may have been the cause:  https://github.com/pristas-peter/wp-graphql-gutenberg/blob/develop/src/PostTypes/block-editor-preview/index.js#L20

**Comment by pristas-peter** [comment]
Thanks, will try to cover these kind of errors in the future with proper tests.
