### ISSUE TITLE
Unable to create/update pages with block type "Cover"

### ISSUE THREAD

**Issue by yjimk** [pristas-peter/wp-graphql-gutenberg#6]
Hi there!

Thanks for putting this together, so far it's been working quite well for me for the block types I've tried so far. 

The block type "cover" however seems to not be working correctly, however. Any create/update of a page with this built in block gets stuck loading, and doesn't finish. The content is also not updated, proving to be a bit of a blocker.

There is an error message that is presented when loading hangs

```
PHP Notice:  Undefined variable: post in /var/www/html/wp-content/plugins/a/plugin.php on line 680
```

Finding this line in the code, I suppose it is possible for $post to be undefined as it is a parameter of the calling function and potentially simply nothing passed in. Unfortunately I can't get a stack trace out to give you more detail. Also not sure if this is the root cause or just a coincidence either, as it is just a warning I don't think it is throwing here.

WordPress: 5.2.2
PHP: 7.2
wp-graphql-gutenberg: 0.0.2
Docker Image: https://hub.docker.com/_/wordpress - wordpress:5-php7.2 (Alpine Linux)

**Comment by pristas-peter** [comment]
Pushed a fix. Please try again.

**Comment by yjimk** [comment]
That has fixed the PHP notice, however unfortunately publish is still not working with the 'Cover' block. No errors present in the console or in any of the logs, sorry I can't give any more information beyond that.

Is it something you're able to reproduce on your side?

**Comment by pristas-peter** [comment]
I'll will try to reproduce it and give you a feedback.

**Comment by pristas-peter** [comment]
Should be working now. If not please reopen. Thanks.

**Comment by yjimk** [comment]
Thanks for that, worked a treat!
