### ISSUE TITLE
HTML comments are all treated as Gutenberg blocks, causes errors for Next Page and Read More blocks

### ISSUE THREAD

**Issue by TylerBarnes** [pristas-peter/wp-graphql-gutenberg#63]
When importing https://github.com/Automattic/theme-tools/blob/master/gutenberg-test-data/gutenberg-test-data.xml

I get this error:
```json
    {
      "debugMessage": "'properties' keyword must be an object, array given",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 6,
          "column": 7
        }
      ],
      "path": [
        "posts",
        "nodes",
        2,
        "blocksJSON"
      ]
    }
```

This appears to be related to the "Gutenberg: Layout Element Blocks" post that is imported.

**Comment by TylerBarnes** [comment]
Ah, looks like the problem is html comments that aren't Gutenberg blocks

```html
<!-- wp:nextpage -->
<!--nextpage-->
<!-- /wp:nextpage -->

<!-- wp:more -->
<!--more-->
<!-- /wp:more -->
```

**Comment by ravewebdev** [comment]
I'm running into this same error if a page includes blocks that are not supported by the current theme. The only workaround has been to manually remove unsupported blocks from each page (which is trivial in my team's case but would be a major problem on a larger site if the theme were to be changed).

**Comment by rodrigo-arias** [comment]
Hi @pristas-peter I am facing this issue, have you had a chance to take a look? Thanks
