### ISSUE TITLE
PHP Fatal error: Uncaught Error: Cannot use object of type GraphQL\\Type\\SchemaConfig as array

### ISSUE THREAD

**Issue by jaydiablo** [pristas-peter/wp-graphql-gutenberg#72]
Wordpress instance just auto-updated WPGraphQL plugin, and now getting a 500 error when trying to load the schema in the wp-admin GraphiQL viewer.

>PHP Fatal error: Uncaught Error: Cannot use object of type GraphQL\\Type\\SchemaConfig as array in wp-content/plugins/wp-graphql-gutenberg-0.3.6/src/Schema/Types/BlockTypes.php:272
>Stack trace:
>#0 wp-includes/class-wp-hook.php(287): WPGraphQLGutenberg\\Schema\\Types\\BlockTypes->WPGraphQLGutenberg\\Schema\\Types\\{closure}(Object(GraphQL\\Type\\SchemaConfig))
>1 wp-includes/plugin.php(212): WP_Hook->apply_filters(Object(GraphQL\\Type\\SchemaConfig), Array)
>2 wp-content/plugins/wp-graphql/src/WPSchema.php(50): apply_filters('graphql_schema_...', Object(GraphQL\\Type\\SchemaConfig))
>3 wp-content/plugins/wp-graphql/src/Registry/SchemaRegistry.php(50): WPGraphQL\\WPSchema->__construct(Object(GraphQL\\Type\\SchemaConfig))
>4 wp-content/plugins/wp-graphql/wp-graphql.php(602): WPGraphQL\\Registry\\SchemaRegistry->get_schema()
>5 wp-content/plugins/wp-graphql/src/Request. 
>in wp-content/plugins/wp-graphql-gutenberg-0.3.6/src/Schema/Types/BlockTypes.php on line 272, referer: https://domain.com/wp-admin/admin.php?page=graphiql-ide

Version of wpgraphql plugin before, that was working, was 1.0.5, version now is 1.1.1.

**Comment by brumfields** [comment]
I am experiencing the same issue. After updating the Wordpress and Gatsby plugins. When I deactivate wp-graphql-gutenberg my graphql url works fine.

**Comment by jaydiablo** [comment]
Yes, de-activating this plugin fixes it, also installing 1.0.5 of the wpgraphql plugin fixes this too. Clearly some incompatibility with the 1.1.x version of wpgraphql but haven't been able to dig much yet.

**Comment by renrizzolo** [comment]
This is the relevant change https://github.com/wp-graphql/wp-graphql/commit/640ea27fc8a2c5af0726df7744c8d33c52c4d867

I've updated the graphql_schema_config filter to work with this change here:
https://github.com/renrizzolo/wp-graphql-gutenberg/tree/fix-schema-config

I guess this would only work with wp-graphql > 1.1.0 or (1.1.1 ?)

**Comment by ravewebdev** [comment]
I'm experiencing this same issue and it's blocking my team's dev work. We need the fixes from WP GraphQL v1.1.1, but also need this Gutenberg plugin so some of our tasks are on-hold until this is fixed.

**Comment by zacscott** [comment]
I have raised a pull request which resolves this issue. It is based on @renrizzolo s work but is backwards compatible with older versions of wp-graphql.

https://github.com/pristas-peter/wp-graphql-gutenberg/pull/75

Merging this would be greatly appreciated, it is affecting a project we are working on.

**Comment by jaydiablo** [comment]
This appears to be fixed with `0.3.7`, I tested against wp-graphql `1.0.5` and `1.1.2` and both the schema and the blocks on a post appear to work as expected.

Thanks @zacscott and @pristas-peter !
