### ISSUE TITLE
Attributes with type "object" returned as string

### ISSUE THREAD

**Issue by Liingon** [pristas-peter/wp-graphql-gutenberg#82]
Block attributes that have the type set to "object" are returned as a string, both in the default blocks and in custom blocks. Is there a way around this?

I've tried [defining properties on the attribute](https://developer.wordpress.org/rest-api/extending-the-rest-api/schema/#objects) on a custom block but that makes no difference.

An example from the default blocks is the media-text block that has a focal point attribute. When I try that in the graphql editor it returns a string like this `"focalPoint": "{\"x\":\"0.19\",\"y\":\"0.72\"}"`

If it's possible to solve this and someone can point me in the right direction I'd be happy to look into making a pull request.

**Comment by gopeter** [comment]
Hi @Liingon, could you please share how you added the custom properties?
