### ISSUE TITLE
Backslash not being returned within content

### ISSUE THREAD

**Issue by mdrayer** [pristas-peter/wp-graphql-gutenberg#9]
The backslash character (`\`) is not being returned within block values. For example, if I have a paragraph block with only a backslash in it, the returned value of `originalContent` is just `<p></p>`. Similarly, if I have a level 2 heading block with a value of `ABC \ 123`, the returned value of `originalContent` is `<h2>ABC  123</h2>`. I have not tested on other core blocks, but I assume they will have similar results. It seems like the backslashes need to be escaped in their return values? As a note, the title field being handled by wp-graphql returns values with escaped characters (i.e. a page title of `Page \ Title` will return `"title": "Page \\ Title"`).

This was tested on WordPress 5.2.4, and latest versions of wp-graphql and wp-graphql-gutenberg.

**Comment by pristas-peter** [comment]
will look into this

**Comment by mdrayer** [comment]
@pristas-peter any updates here?

**Comment by mdrayer** [comment]
Still an issue on wp-graphql-gutenberg v0.1.3. Tested with WP 5.3.0, wp-graphql v0.4.3.

**Comment by pristas-peter** [comment]
Fixed in 9bae1172bc85752e49ca334f1f6a067fda524f5d

Will be included in a new version (0.2.0) with some breaking changes. You can test it out from `develop` branch. Sorry, that it took so long.
